FROM otasys/java:1.8.0_66
MAINTAINER Ahmed Hassanien <ahmed_hassanien@otasys.com>

ADD start.sh /opt/setupAgent.sh
RUN chmod +x /opt/setupAgent.sh

# Default command.
CMD ["sh", "/opt/setupAgent.sh"]
